#pragma once

#define GCODE_ERROR_OK 0
#define GCODE_ERROR_BLOCK_START_INVALID_CHAR 1
#define GCODE_ERROR_DUPLICATED_INTERPOLATION 2
#define GCODE_ERROR_DUPLICATED_WORKPLANE 3
#define GCODE_ERROR_DUPLICATED_POSITIONING_MODE 4
#define GCODE_ERROR_G92_AND_TABLE_MOTION 5
#define GCODE_ERROR_DUPLICATED_MOTOR_COMMAND 6
#define GCODE_ERROR_UNSUPPORTED_COMMAND 7
#define GCODE_ERROR_DUPLICATED_ARGS 8
#define GCODE_ERROR_UNEXPECTED_ARGS 9
#define GCODE_ERROR_INVALID_CIRCLE_PARAMS 10
#define GCODE_ERROR_SPINDLE_TIMEOUT 11
#define GCODE_ERROR_TABLE_TIMEOUT 12
#define GCODE_ERROR_AXIS_LIMIT 13
#define GCODE_ERROR_TABLE_MOTOR 14
#define GCODE_ERROR_SPINDLE_MOTOR 15
#define GCODE_ERROR_EXPECTED_NUMBER 16
#define GCODE_ERROR_MOTION_INTERRUPTED 17